#!/usr/bin/env bash
# Installs Nginx, configures and start the server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 777 /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
