#!/usr/bin/env bash
# redirection

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo chmod -R $USER:$USER /var/www/html
sudo echo 'Hello World!' > /var/www/html/index.html

sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx start
