#!/usr/bin/env bash
# redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html

SERVICE_CONFIG=\
"server {
        listen 80 default_server;
	listen [::]:80 default_server;
	       root /var/www/html;
	index index.html index.html index.nginx-debian.html;

	server_name _;

	location / {
	        try_files \$uri \$uri/ =404;
	}
        error_page 404 /404.html;
	location /404.html {
	    internal;
        }

        if (\$request_filename ~ redirect_me){
	    rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo echo '$SERVER_CONFIG' > /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
	service nginx start
else
	service nginx restart
fi;
