#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y haproxy

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo "ENABLED=1">>/etc/default/haproxy

config=\
"
backend myservers_backend
	balance roundrobin
	server 5061-web-01 44.200.176.121:80 check
	server 5061-web-02 44.200.77.205:80 check
frontend myservers_frontend
	bind *:80
	mode http
	default_backend myservers_backend
"
echo "$config">>/etc/haproxy/haproxy.cfg

sudo service haproxy restart
