#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.
# displays hours from 0 to 12
# displays minutes from 1 to 59

H=0

while [ $H -le 12 ]
do
	echo "Hour: $H"
	m=1
	while [ $m -le 59 ]
	do
		echo "$m"
		(( m++ ))
	done
	((H++))
done
